#!/srvr/cs3311psql/lib/php525/bin/php
<?php

define("LIB_DIR","/import/adams/1/cs3311/public_html/19s1/assignments/a2");
require_once(LIB_DIR."/db.php");

define("DB_CONNECTION","dbname=a2");

if ($argc < 2) exit("Usage: ./acting <ActorName>\n");
$name = $argv[1];

$db = dbConnect("dbname=a2");

$qry = <<<xxSQLxx
select m.title, d.name, m.year, m.content_rating, r.imdb_score
from   Actor a, Acting c, Rating r, Movie m
left outer join Director d on m.director_id = d.id
where  a.name ~* %s and
a.id = c.actor_id
and c.movie_id = m.id
and m.id=r.movie_id
order by m.year, m.title;
xxSQLxx;

$res = dbQuery($db, mkSQL($qry,$name));
$c = dbNResults($res);
if ($c == 0) exit;
$i = 1;
while ($t = dbNext($res)) {
    printf("%d. %s ", $i++, $t["title"]);
    if ($t["name"]) {
        printf("-- %s (", $t["name"]);
    } else {
        printf("(");
    }

    $arr = array($t["year"],$t["content_rating"],$t["imdb_score"]);
    $arr = array_filter($arr);

    $str = implode(', ', $arr);
    printf("%s)\n", $str);
}
?>
